name: Release on SemVer Tag Push

on:
  push:
  # pull_request event is required only for autolabeler
    tags:
    - 'v*.*.*'
jobs:
  release-on-tag-push:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3 | sed -r 's/^.{1}//' )
      # Drafts your next Release notes as tags are pushed to origin
      - name: draft-release
        id: draft-release-id
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: build deb
        uses: jiro4989/build-deb-action@v2
        with:
          package: solar
          package_root: solar_raspbian
          maintainer: Oli
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'armel'
          depends: 'python3, wiringpi'
          desc: 'ladex10 systemd service '
      - name: Upload Deb as Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft-release-id.outputs.upload_url }}
          # file name is build like this: ${INPUT_PACKAGE}_${FIXED_VERSION}_${INPUT_ARCH}.deb, sadly not passed as actions output :(
          asset_path: ./solar_${{ steps.get_version.outputs.VERSION }}_armel.deb
          asset_name: solar_${{ steps.get_version.outputs.VERSION }}_armel.deb
          asset_content_type: application/deb