name: build

on:
  pull_request:
    types: closed

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build deb
        uses: jiro4989/build-deb-action@v2
        with:
          package: solar
          package_root: solar_raspbian
          maintainer: Oli
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'armel'
          depends: 'python3, wiringpi'
          desc: 'ladex10 systemd service '
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: solar-debian-package
          path: "*.deb"
      - name: Tag and prepare release
        id: tag_and_prepare_release
        uses: K-Phoen/semver-release-action@master
        with:
          release_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload release notes
        if: steps.tag_and_prepare_release.outputs.tag
        uses: Roang-zero1/github-create-release-action@master
        with:
          created_tag: ${{ steps.tag_and_prepare_release.outputs.tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}