name: build

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: dep build
        uses: jiro4989/build-deb-action@v2
        with:
          package: solar
          package_root: solar_raspbian
          maintainer: Oli
          version: ${{ github.ref }} # refs/tags/v*.*.*
          arch: 'armel'
          depends: 'python3'
          desc: 'ladex10 service with relay control logic via rapsi GPIO pins'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: solar-debian-package
          path: *.deb